In [1]:
import numpy as np

In [2]:
S = np.array([[10, 100, 1000],[100, 1000, 10000]])
M1 = np.array([[0.5, 0.25, 0.25],[0.25, 0.50, 0.25],[0.25, 0.25, 0.50]])
M2 = np.array([[1, 0, 0],[0, 1, 0],[0, 0, 1]])
Mstack = np.stack((M1, M2), axis=2)

In [3]:
print(S @ M1)

[[ 280.   302.5  527.5]
 [2800.  3025.  5275. ]]


In [4]:
M_expanded = np.broadcast_to(np.atleast_3d(M1), (3, 3, 2))
Sv = np.einsum('ik,kji->ij', S, M_expanded)
print(Sv)

[[ 280.   302.5  527.5]
 [2800.  3025.  5275. ]]


In [5]:
M_expanded = np.broadcast_to(np.atleast_3d(Mstack), (3, 3, 2))
Sv = np.einsum('ik,kji->ij', S, M_expanded)
print(Sv)

[[  280.    302.5   527.5]
 [  100.   1000.  10000. ]]


In [8]:
# define sizes
n_age = 10
n_space = 5

# define test matrices
S = np.random.rand(*(n_age, n_space))
M_2d = np.random.rand(*(n_space, n_space))
M_3d = np.broadcast_to(np.atleast_3d(M_2d), (n_space, n_space, n_age))

# define matrix multiplication
def mult(S, M, n_age, n_space):
    return np.einsum('ik,kji->ij', S, np.broadcast_to(np.atleast_3d(M), (n_space, n_space, n_age)))

# try it out
print(mult(S, M_2d, n_age, n_space))
print(mult(S, M_3d, n_age, n_space))  
generalized_matrix_transform(S, M_2d, 0)

[[1.66774599 1.69932323 1.03209605 1.15486665 1.3015074 ]
 [1.96348436 1.82648075 1.24083853 1.526271   1.64955253]
 [1.95726155 1.88908682 1.52624716 1.75056425 1.84253241]
 [2.0188896  1.19039821 1.23786125 1.39647585 1.33256348]
 [1.48061452 1.13696513 1.32585257 1.78506232 1.34314997]
 [1.68199002 1.44837392 1.11191001 0.97456161 1.11525654]
 [2.25618926 2.00519101 1.74455024 2.25827405 1.82163469]
 [1.86784881 1.7511435  1.57177564 1.73109914 1.62390964]
 [1.81556687 1.39673291 1.37749307 1.57520185 1.80375939]
 [2.24518886 2.31473638 1.77735021 2.06051645 2.21408796]]
[[1.66774599 1.69932323 1.03209605 1.15486665 1.3015074 ]
 [1.96348436 1.82648075 1.24083853 1.526271   1.64955253]
 [1.95726155 1.88908682 1.52624716 1.75056425 1.84253241]
 [2.0188896  1.19039821 1.23786125 1.39647585 1.33256348]
 [1.48061452 1.13696513 1.32585257 1.78506232 1.34314997]
 [1.68199002 1.44837392 1.11191001 0.97456161 1.11525654]
 [2.25618926 2.00519101 1.74455024 2.25827405 1.82163469]
 [1.86784881 

array([[1.66774599, 1.69932323, 1.03209605, 1.15486665, 1.3015074 ],
       [1.96348436, 1.82648075, 1.24083853, 1.526271  , 1.64955253],
       [1.95726155, 1.88908682, 1.52624716, 1.75056425, 1.84253241],
       [2.0188896 , 1.19039821, 1.23786125, 1.39647585, 1.33256348],
       [1.48061452, 1.13696513, 1.32585257, 1.78506232, 1.34314997],
       [1.68199002, 1.44837392, 1.11191001, 0.97456161, 1.11525654],
       [2.25618926, 2.00519101, 1.74455024, 2.25827405, 1.82163469],
       [1.86784881, 1.7511435 , 1.57177564, 1.73109914, 1.62390964],
       [1.81556687, 1.39673291, 1.37749307, 1.57520185, 1.80375939],
       [2.24518886, 2.31473638, 1.77735021, 2.06051645, 2.21408796]])

In [99]:
# define sizes
n_age = 10
n_space = 5

# define test matrices
S = np.random.rand(*(n_age, n_space))
N_2d = np.random.rand(*(n_age, n_age))
N_3d = np.broadcast_to(np.atleast_3d(N_2d), (n_age, n_age, n_space))

# define matrix multiplication
def mult_N(S, N, n_age, n_space):
    return np.transpose(np.einsum('ik,kji->ij', np.transpose(S), np.broadcast_to(np.atleast_3d(N), (n_age, n_age, n_space))))

# try it out
print(mult_N(S, N_2d, n_age, n_space).shape)
print(mult_N(S, N_3d, n_age, n_space))  

(10, 5)
[[3.29288984 3.74772378 2.83267123 3.39862312 2.83108313]
 [2.41960994 2.58600059 2.39249892 2.3209429  1.60640578]
 [2.14181818 2.70332277 2.40009359 2.14684112 1.63758882]
 [2.8186203  3.0740728  3.25001238 2.87077379 1.87111046]
 [1.93879989 3.01434913 2.63082601 2.8131129  1.96887555]
 [3.48398738 3.80333882 3.35133043 2.9490236  2.24755637]
 [2.07925402 2.40816425 1.94400386 2.38458083 1.26946859]
 [2.65128536 3.04567165 1.45264121 2.81272636 1.43589964]
 [2.86462843 2.8876224  2.73210061 2.56939165 2.0714777 ]
 [2.09263153 2.46768173 1.78372601 1.87862137 1.06103423]]


In [7]:
def generalized_matrix_transform(X, W, dim):
    """
    A generalized function to compute a transformed matrix based on a weight matrix.
    
    This function can be used to compute the number of individuals on every spatial patch post-mobility 
    or to compute the infection pressure, depending on the interpretation of dimensions.
    
    Parameters
    ==========
    X : np.ndarray
        Input matrix. Size (n_age, n_location) or (n_group1, n_group2).
    W : np.ndarray
        Weight matrix. Variable size, either of shape (n_group2, n_group2) (2D case) 
        or (n_group2, n_group2, n_group1) (3D case).
        The 3D case corresponds to having an (n_group2, n_group2)-shaped matrix for each group in the other dimension.
    dim : int
        The dimension along which the 3D weight matrix is applied. Use 0 for age, 1 for location.
    
    Returns
    =======
    X_transformed : np.ndarray
        The transformed matrix.
        Behavior:
            2D-case: equivalent to np.matmul(X, W)
            3D-case: equivalent to matrix multiplication Xv_{ij} = sum_{l}[x_{il} * w_{lji}] if dim=0
                     or Xv_{ij} = sum_{l}[x_{lj} * w_{lki}] if dim=1
    """
    if dim == 0:
        return np.einsum('ik,kji->ij', X, np.broadcast_to(np.atleast_3d(W), (W.shape[0], W.shape[0], X.shape[dim])))
    elif dim == 1:
        return np.einsum('ki,kjl->ij', X, np.broadcast_to(np.atleast_3d(W), (W.shape[0], W.shape[0], X.shape[dim])))
    else:
        raise ValueError("Invalid dimension. Use 0 for age, 1 for location.")


In [101]:
generalized_matrix_transform(np.transpose(S), N_2d, 0)

array([[3.29288984, 2.41960994, 2.14181818, 2.8186203 , 1.93879989,
        3.48398738, 2.07925402, 2.65128536, 2.86462843, 2.09263153],
       [3.74772378, 2.58600059, 2.70332277, 3.0740728 , 3.01434913,
        3.80333882, 2.40816425, 3.04567165, 2.8876224 , 2.46768173],
       [2.83267123, 2.39249892, 2.40009359, 3.25001238, 2.63082601,
        3.35133043, 1.94400386, 1.45264121, 2.73210061, 1.78372601],
       [3.39862312, 2.3209429 , 2.14684112, 2.87077379, 2.8131129 ,
        2.9490236 , 2.38458083, 2.81272636, 2.56939165, 1.87862137],
       [2.83108313, 1.60640578, 1.63758882, 1.87111046, 1.96887555,
        2.24755637, 1.26946859, 1.43589964, 2.0714777 , 1.06103423]])